# Site settings
title: Jim
email: contact@jimli.net
description: >
  Placeholder
baseurl: ""
url: "https://jimzli.github.io"
github_username: jimzli
linkedin_username:
stackoverflow_username:
stackoverflow_usernumber:
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman